title: Australian Structural Biology Computing
# This appears in the html browser tab for the site title (seen mostly by search engines, not users)

topnav_title: Australian Structural Biology Computing 
# Optional: this appears on the top navigation bar next to the main_logo.svg icon

description: "A website for the Australian Structural Biology Computing community."
# Metadata description of the website

# Following AusBioCommons minimal gh-pages with remote deploy -  https://github.com/AustralianBioCommons/how-to-guides/blob/main/_config.yml
remote_theme: ELIXIR-Belgium/elixir-toolkit-theme

exclude:
  - README.md
  - vendor
  - Gemfile

defaults:
# Define here page metadata attributes for all pages at once or on specific directories. More information: https://jekyllrb.com/docs/configuration/front-matter-defaults/
  -
    scope:
      path: ""
      type: "pages"
    values:
      permalink: /:basename
      layout: "page"
      sidebar: main
  - scope:
      path: "pages"
      type: "pages"
    values:
      sidebar: main
  - scope:
      path: "workgroup_template_directory"
      type: "pages"
    values:
      sidebar: workgroup_example

theme_variables: 
  # git_host: GitHub
   back_to_top: true
  # privacy_statement_url: /privacy
  # github_buttons: 
  #   position: top
  #   edit_me: true
  #   open_issue: true
  #   history: true
  # headings:
  #   related-pages: Related pages
  #   more-information-tiles: More information
  #   resource-table-all: Tools and resources on this page
  #   resource-table-all-collapse: false
  #   affiliation-tiles-page: Affiliations
  #   contributor-minitiles-page: Contributors
  # toc:
  #   min_headings: 2
  #   headings: 'h2'
   topnav:
    # theme: light
    brand_logo: assets/img/aus-struct-bio-computing-2.png
    # github: true
    # twitter: false
  # theme_color: 0d6efd
  # fonts:
  #   - url towards a font

plugins:
  - elixir-toolkit-theme-plugins
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-github-metadata
  - jemoji
  - webrick

# --- Missing in gitlab: ---
# github:
#   repository_url: https://github.com/ELIXIR-Belgium/elixir-toolkit-theme
#   source:
#     branch: main

